### ISSUE TITLE
Configuring the deployment process

### ISSUE THREAD

**Issue by lk-geimfari** [roskomsvoboda/censortracker_backend#4]
Since we working on Censor Tracker in Github, but our CI/CD is Gitlab we need to configure our deployment process somehow. Maybe we can create a mirror of this repository on Gitlab or something. 

@HellsYeah @msva What do you think?

**Comment by HellsYeah** [comment]
Another way is setting up the Github Actions, right?

**Comment by lk-geimfari** [comment]
@HellsYeah The main question is "How to securely deploy the project on our server?". I'm not sure that we can make Github Actions work with our server, but I'm also not sure in the opposite, soo...
