### ISSUE TITLE
Reduce domain duplication

### ISSUE THREAD

**Issue by lk-geimfari** [roskomsvoboda/censortracker_backend#6]
Create a `CensorshipCase` model with `m2o` link to `Domain`. In `CensorshipCase`, we will store specific information on locks and the client (hash, region, etc.), for which the lock was detected, and in `Domain` only domains.

`CensorshipCase` can have any other much appropriate name.

Example:

```python
class Domain(models.Model):
    domain = models.CharField(..., unique=True)
    ...


class CensorshipCase(models.Model):
    domain = models.ForeignKey(Domain, related_name='domains', ...)
    ...
```

**Comment by HellsYeah** [comment]
`CensorshipCase` is quite long classname. `Case` is just enough in app context.

Endpoint `POST /domain/` will become `POST /case/`. New domains will be added from new cases. Endpoint `POST /case/` require `domain_name` field that doesn't match `Case.domain` explicitly.

Not to forget to update readme

**Comment by lk-geimfari** [comment]
@HellsYeah I agree. When you'll finish, do not forget to create PR to CensorTracker with related changes: [censortracker/blob/master/src/chrome/js/core/settings.js#L17](https://github.com/roskomsvoboda/censortracker/blob/master/src/chrome/js/core/settings.js#L17)
